name: pricing_engine
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - altair=6.0.0=py310haa95532_0
  - arrow-cpp=21.0.0=h6358905_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=py310haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - blinker=1.9.0=py310haa95532_1
  - bottleneck=1.4.2=py310h540bb41_1
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=6.2.2=py310haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - click=8.2.1=py310haa95532_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310h214f63a_0
  - cycler=0.12.1=py310haa95532_0
  - debugpy=1.8.19=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py310h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py310haa95532_0
  - gitpython=3.1.45=py310haa95532_0
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.2=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py310haa95532_1
  - jsonschema-specifications=2025.9.1=py310haa95532_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.17.0=h97e0424_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxgboost=3.1.2=h585ebfc_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.10.7=py310haa95532_0
  - matplotlib-base=3.10.7=py310h26e45b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - narwhals=2.7.0=py310haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py310h7660c64_0
  - numpy=2.2.5=py310h7894be3_2
  - numpy-base=2.2.5=py310h7794460_2
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=py310haa95532_0
  - pcre2=10.46=h5740b90_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=5.29.3=py310h5da7b33_0
  - psutil=7.1.3=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=py310haa95532_0
  - pyarrow=21.0.0=py310h42c1672_1
  - pycparser=2.23=py310haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py310haa95532_0
  - pyqt=6.9.1=py310h12ec796_0
  - pyqt6-sip=13.10.2=py310h630b2a1_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.16=h4607a30_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=py310haa95532_0
  - pywin32=311=py310h282bd7d_1
  - pyyaml=6.0.3=py310hb9a58be_0
  - pyzmq=27.1.0=py310h535538e_0
  - qtbase=6.9.2=h06bae2a_5
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py310haa95532_0
  - requests=2.32.5=py310haa95532_1
  - rpds-py=0.28.0=py310h114bc41_0
  - scikit-learn=1.7.1=py310h3fbe716_0
  - scipy=1.15.3=py310h1bbe36f_1
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=80.9.0=py310haa95532_0
  - sip=6.12.0=py310h706e071_0
  - six=1.17.0=py310haa95532_0
  - smmap=5.0.2=py310haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py310h02ab6af_0
  - streamlit=1.52.2=py310haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tenacity=9.1.2=py310haa95532_0
  - threadpoolctl=3.5.0=py310h4442805_1
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.4=py310h02ab6af_0
  - tqdm=4.67.1=py310h4442805_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.1=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py310haa95532_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xgboost=3.1.2=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\parth\miniconda3\envs\pricing_engine
